# Add and remove of rows and columns

## `Adding and Removing columns:` it is basically same thing that we did updating values we can create a column and pass series of values that column to hava

In [3]:
import pandas as pd

In [4]:
people1 = {'first' : ['Isaac','Charles','Stephen'],
           'last'  : ['Newton','Darwin','Hawking'],
           'email' : ['Newton@gmail.com','Darwin@gmail.com','Hawking@gmail.com']}

In [7]:
df_1 = pd.DataFrame(people1)
df_1

     first     last              email
0    Isaac   Newton   Newton@gmail.com
1  Charles   Darwin   Darwin@gmail.com
2  Stephen  Hawking  Hawking@gmail.com

In [34]:
people2 = {'first' : ['Thomas','Albert'],
           'last'  : ['Edition','Einstein'],
           'email' : ['Thomas@gmail.com','Einstein@gmail.com']}

In [35]:
df_2 = pd.DataFrame(people2)
df_2

    first      last               email
0  Thomas   Edition    Thomas@gmail.com
1  Albert  Einstein  Einstein@gmail.com

In [9]:
df_1

     first     last              email
0    Isaac   Newton   Newton@gmail.com
1  Charles   Darwin   Darwin@gmail.com
2  Stephen  Hawking  Hawking@gmail.com

In [14]:
df_1['full_name'] = df_1['first'] + ' ' + df_1['last']

In [15]:
df_1

     first     last              email        full_name
0    Isaac   Newton   Newton@gmail.com     Isaac Newton
1  Charles   Darwin   Darwin@gmail.com   Charles Darwin
2  Stephen  Hawking  Hawking@gmail.com  Stephen Hawking

In [16]:
df_1.drop(columns = ['first','last'],inplace = True)

In [17]:
df_1

               email        full_name
0   Newton@gmail.com     Isaac Newton
1   Darwin@gmail.com   Charles Darwin
2  Hawking@gmail.com  Stephen Hawking

In [19]:
df_1['full_name'].str.split(' ')

0       [Isaac, Newton]
1     [Charles, Darwin]
2    [Stephen, Hawking]
Name: full_name, dtype: object

In [20]:
df_1['full_name'].str.split(' ',expand = True)

         0        1
0    Isaac   Newton
1  Charles   Darwin
2  Stephen  Hawking

In [22]:
df_1[['first','last']] = df_1['full_name'].str.split(' ',expand = True)

In [23]:
df_1

               email        full_name    first     last
0   Newton@gmail.com     Isaac Newton    Isaac   Newton
1   Darwin@gmail.com   Charles Darwin  Charles   Darwin
2  Hawking@gmail.com  Stephen Hawking  Stephen  Hawking

## `Adding and Removing the rows :` first we might just want to add a single row to our dataframe of new data and second may be we want to combine two dataframes by appending the rows of one to another

In [ ]:
# df_1.append({'fist':'Marie Curie'}) # uncomment to see "TypeError:Can only append a dict if ignore_index=True"

In [25]:
df_1.append({'fist':'Marie','last' : 'Curie'},ignore_index=True)

C:\Users\kalag\AppData\Local\Temp\ipykernel_10596\2360739798.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_1.append({'fist':'Marie','last' : 'Curie'},ignore_index=True)

               email        full_name    first     last   fist
0   Newton@gmail.com     Isaac Newton    Isaac   Newton    NaN
1   Darwin@gmail.com   Charles Darwin  Charles   Darwin    NaN
2  Hawking@gmail.com  Stephen Hawking  Stephen  Hawking    NaN
3                NaN              NaN      NaN    Curie  Marie

### Adding one dataframe into another dataframe

In [27]:
df_1

               email        full_name    first     last
0   Newton@gmail.com     Isaac Newton    Isaac   Newton
1   Darwin@gmail.com   Charles Darwin  Charles   Darwin
2  Hawking@gmail.com  Stephen Hawking  Stephen  Hawking

In [36]:
df_2

    first      last               email
0  Thomas   Edition    Thomas@gmail.com
1  Albert  Einstein  Einstein@gmail.com

In [37]:
df = df_1.append(df_2,ignore_index=True)
df

C:\Users\kalag\AppData\Local\Temp\ipykernel_10596\2543546101.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df_1.append(df_2,ignore_index=True)

                email        full_name    first      last
0    Newton@gmail.com     Isaac Newton    Isaac    Newton
1    Darwin@gmail.com   Charles Darwin  Charles    Darwin
2   Hawking@gmail.com  Stephen Hawking  Stephen   Hawking
3    Thomas@gmail.com              NaN   Thomas   Edition
4  Einstein@gmail.com              NaN   Albert  Einstein

In [38]:
# drop the row

df.drop(index = 4)   # 4th inde were deleted to get perminent place inplace = True

               email        full_name    first     last
0   Newton@gmail.com     Isaac Newton    Isaac   Newton
1   Darwin@gmail.com   Charles Darwin  Charles   Darwin
2  Hawking@gmail.com  Stephen Hawking  Stephen  Hawking
3   Thomas@gmail.com              NaN   Thomas  Edition

In [45]:
ftr = df['last'] == 'Edition'
df.drop(index = df[ftr].index)    # remove the value of last = Edition

                email        full_name    first      last
0    Newton@gmail.com     Isaac Newton    Isaac    Newton
1    Darwin@gmail.com   Charles Darwin  Charles    Darwin
2   Hawking@gmail.com  Stephen Hawking  Stephen   Hawking
4  Einstein@gmail.com              NaN   Albert  Einstein

# Sorting Data

In [46]:
df

                email        full_name    first      last
0    Newton@gmail.com     Isaac Newton    Isaac    Newton
1    Darwin@gmail.com   Charles Darwin  Charles    Darwin
2   Hawking@gmail.com  Stephen Hawking  Stephen   Hawking
3    Thomas@gmail.com              NaN   Thomas   Edition
4  Einstein@gmail.com              NaN   Albert  Einstein

In [47]:
df.sort_values(by = 'last')   # sorted based on last column  will sort ascending order

                email        full_name    first      last
1    Darwin@gmail.com   Charles Darwin  Charles    Darwin
3    Thomas@gmail.com              NaN   Thomas   Edition
4  Einstein@gmail.com              NaN   Albert  Einstein
2   Hawking@gmail.com  Stephen Hawking  Stephen   Hawking
0    Newton@gmail.com     Isaac Newton    Isaac    Newton

In [49]:
df.sort_values(by = 'last' , ascending = False)    # sorted based on last column ascending = False will sort decending order

                email        full_name    first      last
0    Newton@gmail.com     Isaac Newton    Isaac    Newton
2   Hawking@gmail.com  Stephen Hawking  Stephen   Hawking
4  Einstein@gmail.com              NaN   Albert  Einstein
3    Thomas@gmail.com              NaN   Thomas   Edition
1    Darwin@gmail.com   Charles Darwin  Charles    Darwin

In [48]:
df.sort_values(by = ['first','last'])

                email        full_name    first      last
4  Einstein@gmail.com              NaN   Albert  Einstein
1    Darwin@gmail.com   Charles Darwin  Charles    Darwin
0    Newton@gmail.com     Isaac Newton    Isaac    Newton
2   Hawking@gmail.com  Stephen Hawking  Stephen   Hawking
3    Thomas@gmail.com              NaN   Thomas   Edition

In [51]:
df.sort_values(by = ['first','last'] , ascending = [True,False])

                email        full_name    first      last
4  Einstein@gmail.com              NaN   Albert  Einstein
1    Darwin@gmail.com   Charles Darwin  Charles    Darwin
0    Newton@gmail.com     Isaac Newton    Isaac    Newton
2   Hawking@gmail.com  Stephen Hawking  Stephen   Hawking
3    Thomas@gmail.com              NaN   Thomas   Edition

In [52]:
# the indexes are in sorrted we can use sort index method
df.sort_index()

                email        full_name    first      last
0    Newton@gmail.com     Isaac Newton    Isaac    Newton
1    Darwin@gmail.com   Charles Darwin  Charles    Darwin
2   Hawking@gmail.com  Stephen Hawking  Stephen   Hawking
3    Thomas@gmail.com              NaN   Thomas   Edition
4  Einstein@gmail.com              NaN   Albert  Einstein

### Sort a single columns we can easily just sort i single serie as well series also have sort index method

In [55]:
df['email'].sort_values()

1      Darwin@gmail.com
4    Einstein@gmail.com
2     Hawking@gmail.com
0      Newton@gmail.com
3      Thomas@gmail.com
Name: email, dtype: object

### On stackoverflow data

In [63]:
df = pd.read_csv(r"C:\Users\kalag\Downloads\stack-overflow-developer-survey-2019\survey_results_public.csv",index_col = 'Respondent')
schema_df = pd.read_csv(r"C:\Users\kalag\Downloads\stack-overflow-developer-survey-2019\survey_results_schema.csv",index_col = 'Column')

In [64]:
pd.set_option('display.max_columns',80)

In [65]:
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,...,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",...,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",...,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",...,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [66]:
df.columns

Index(['MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment',
       'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther',
       'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro',
       'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'JobSeek',
       'LastHireDate', 'LastInt', 'FizzBuzz', 'JobFactors', 'ResumeUpdate',
       'CurrencySymbol', 'CurrencyDesc', 'CompTotal', 'CompFreq',
       'ConvertedComp', 'WorkWeekHrs', 'WorkPlan', 'WorkChallenge',
       'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests',
       'PurchaseHow', 'PurchaseWhat', 'LanguageWorkedWith',
       'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [68]:
df.sort_values(by = ['Country','ConvertedComp'] , ascending = [True,False])

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,...,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
63129,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,"Yes, full-time",I never completed any formal education,NaN,Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",NaN,Less than 1 year,Younger than 5 years,1,Very dissatisfied,Very dissatisfied,Very confident,Yes,Yes,I am actively looking for a job,I've never had a job,Write any code,Yes,How widely used or impactful my work output wo...,I had a negative experience or interaction at ...,AED,United Arab Emirates dirham,648838511.0,Monthly,1000000.0,168.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work,It's complicated,"Other place, such as a coworking space or cafe",Far below average,No,NaN,NaN,...,MySQL,MySQL,Android;iOS;Windows;WordPress;Other(s):,Android;iOS;Windows;WordPress;Other(s):,Angular/Angular.js;Express;jQuery;Laravel;Othe...,Angular/Angular.js;Express;jQuery;Laravel;Othe...,Ansible;Apache Spark;Torch/PyTorch,Apache Spark;Torch/PyTorch,Android Studio;Atom;Coda;Eclipse;Emacs;IPython...,Windows,"Outside of work, for personal projects",Accepting Bitcoin or other coins and tokens as...,Useful across many domains and could change ma...,Yes,Yes,Yes,I don't use social media,Online,UserID,NaN,I have never visited Stack Overflow (before to...,Find answers to specific questions,Less than once per week,Stack Overflow was much faster,0-10 minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a jo...",NaN,"No, not at all",NaN,Tech articles written by other developers,NaN,NaN,NaN,NaN,NaN,Yes,Too short,Easy
50499,"I am not primarily a developer, but I write co...",Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A health science (ex. nursing, pharmacy, radio...",Participated in a full-time developer training...,"10,000 or more employees",Data or business analyst;Database administrato...,7,27,7,Very dissatisfied,Very dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",More than 4 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Opportunities for professional development;Div...,"Something else changed (education, award, medi...",AFN,Afghan afghani,960000.0,Monthly,153216.0,40.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Time spent com...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",8.0,"Yes, it's not part of our process but the deve...",...,Microsoft SQL Server;PostgreSQL;SQLite,MariaDB;MongoDB;Microsoft SQL Server;PostgreSQ...,NaN,Android,ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery;React.js;Vue.js,.NET,.NET;.NET Core;Node.js;Xamarin,Visual Studio,Windows,I do not use containers,Implementing our own cryptocurrency,NaN,Yes,Yes,Yes,WhatsApp,Online,Login,2013,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,NaN,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
39258,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Database administrator;Designer;Developer, bac...",2,22,1,Very satisfied,Very satisfied,Very confident,No,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",AFN,Afghan afghani,120000.0,Monthly,19152.0,49.0,There is a schedule and/or spec (made by me or...,Not enough people for the workload;Time spent ...,Less than once per month / Never,Office,Far above average,"Yes, because I see value in code review",10.0,"Yes, it's not part of our process but the deve...",...,MariaDB;MongoDB;MySQL;PostgreSQL,Couchbase;Firebase;MariaDB;MongoDB;Redis,Android;AWS;Linux;Windows;WordPress,Android;AWS;Docker;Heroku;iOS;Linux;Raspberry ...,Angular/Angular.js;Drupal;Express;Laravel,Angular/Angular.js;Drupal;Express,Cordova;Node.js,Hadoop;Node.js,Notepad++;PHPStorm;Vim;Visual Studio Code,Linux-based,Production,NaN,NaN,Yes,Yes,No,Facebook,Online,Login,2016,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,Yes,NaN,"Yes, somewhat",NaN,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,East Asian;South Asian,Yes,Too long,Easy
58450,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Developer, desktop or ente...",6,20,2,Neither satisfied nor dissatisfied,Slightly satisfied,Very confident,Yes,Yes,I am actively looking for a job,1-2 years ago,"Write code by hand (e.g., on a whiteboard);Com...",No,"Languages, frameworks, and other technologies ...",I had a negative experience or interaction at ...,AFN,Afghan afghani,110000.0,Monthly,17556.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment,It's complicated,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process",...,MySQL;PostgreSQL,MySQL;PostgreSQL,Linux;Windows,Windows,NaN,Spring,NaN,Node.js,IntelliJ;Notepad++,Windows,Development,Accepting Bitcoin or other coins and tokens as...,Useful for immutable record keeping outside of...,Yes,Yes,Yes,Facebook,Online,Handle,NaN,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, definitely",A lot less welcome now than last year,Tech articles written by other developers,26.0,Man,No,Straight / Heterosexual,South Asian,No,Too long,Neither easy nor difficult
7085,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",2-9 employees,"Developer, full-stack",7,19,6,Slightly dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,AFN,Afghan afghani,90000.0,Monthly,14364.0,30.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Lack of s...,About half the time,Office,Average,"Yes, because I see value in code review",3.0,NaN,...,MySQL,MongoDB;MySQL;Redis,Linux;MacOS;Other(s):,Linux;MacOS;Other(s):,jQuery;Laravel;Vue.js,ASP.NET;jQuery;Laravel;Vue.js,NaN,React Native,Sublime Text;Visual Studio Code,MacOS,"Development;Outside of work, for personal proj...",NaN,NaN,Yes,Also Yes,Yes,Instagram,Online,UserID,2016,Multiple times per day,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,60+ minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Industry news about technologies you're intere...,26.0,Man,NaN,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88062,NaN,No,Never,"OSS is, on average, of LOWER quality than prop...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88076,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df['ConvertedComp'].nlargest(10)   # we get 10 largesalary

Respondent
58      2000000.0
102     2000000.0
166     2000000.0
436     2000000.0
452     2000000.0
491     2000000.0
539     2000000.0
770     2000000.0
789     2000000.0
1232    2000000.0
Name: ConvertedComp, dtype: float64

In [71]:
df['ConvertedComp'].nsmallest(10) # we get 10 small salary

Respondent
280     0.0
293     0.0
722     0.0
1105    0.0
1501    0.0
1685    0.0
1782    0.0
2019    0.0
2095    0.0
2665    0.0
Name: ConvertedComp, dtype: float64